sudo: required

env:
  global:
    - secure: "tikkEdzV2V6CPAmoRDsM44aEngMYKozaag0gtK12kvDPOPS5UuR0Lc6ZOaKzYI0XMHSo2tmTuAoNDYzElw962OQyc2VgJEJ5/Wup/2LE6L0d6QM4UddRaNGY4zKZ+2jQ/nS5IT1dII0/yVrwJFoUm7Jgzq0C6fQM1gGdJ6B86cCmEXmJsyX8PLgGkQdyFgRIHrEJXXqyHqEYz9n9/sBLM7L22xe50XSc9MO46eA4H5xzCy1d6ONROe3elbj7UpqPs8ilTVliDQrfn5J7CoSiJeGHosaqTzBkPAcolhsOqG1lDK7zEyY/XIv6mVnfso4Xwh37HRmrpz1oMTVjpttgsHf0wX074V1nEp9IrqAqdtDpQSYt7A7mj9oOTrPzweZG7+ISod+IVvBU4Qfv6WDJPEpBNvXjkf5tAa2QJCl3CtlC0M9q7xFobdmaSPCvCged8Y/CLIL4m8dmJ3e50q4pXa58c0ZUwzGVM844S22SrJc8LgQuIUor+gklmwfOpnh8Dnq9cSoEsP5rYQFY7WWT/ii/uHzmHCm1H4lfIoEvSKNLKGvSeonWZtDhEsYTaHJt9r6VdUjRahFhywFcBLWCuEC7udLK5Dd5mESO9C2Vq+prUI9VZ2sOvDwO8bjmodzeDPpZwlKTHEGLljPddahCOqoLZD2kNgPts94qaLL57ws="
    - secure: "Pekpe7lUOdloE/nfBkV11Z+4Z8VmUcvx+x9aqs4ydqsXvKEhZiUcQKoipJyooydF8UQEHNKavapHJrSBiFg3URAFnpsobVCxmUrXYhIO5VSYlVdSq4966q7dS6Lvq6EPWJevpPnzcmuN91HDzgeIOSWZVu4S3uQmMOTWQKewZqnlpLXn5wrmyoDvq4vrunTLba53+BKRGgmFcWle4f2cruJv8Gb9Lrtw85n2lO7N//srScm/U1+46U9U81vzYYbVoVGU9/a0EJVV+z8jSoM3iTtt7qwqBvNQ8mhuXkB2a2y+XgCl8Q2C0BOjuKRvoi6wx7uZCfezcIcB14XDEmtE7VakErciVMpHZjvBeG8IWuSu91zZK8jeXnFxFSXUQoj+nwmdDpmjVctHJ8z7ukb0r9aBPhYufcidM1rREmAiUSrt8yZr9RiFYQagPQluw1VVCidDxyBMzVoQyPERdIQTPdIqsdHx6YoY704LnPOoRplC31EBG8qjtyvVj6ALXM/UiIInP/LTyxuYmugxoQsvz2photcdW3spIcvd886pWttFy6twvwaeSwDdBtv8iDB3PygH8ZatWrfrK1VtZnK32kqOXTvjxaW9C+Psh+I74w9er1WEVWhkKQSRKp7OoKHu9giqTM6neOeOR0za3cvfPG0nPxX+jCfsgxHF2Rco+Xw="
    - secure: "A3hGQ0Z916rRISbNrJ7pr3/T8tXZnOkdFV5D/k0+Q4hxfTHIepJkz1PbCXxnu/ZfdQsYoShbrzodothXJiBNh1eNhL47A6jLb87Oiml6IOmL7kp8uCGrb455YXhWgorrVQ2YNOERgkesNnuFEdawSDeLsOcCCu/lx9B5BEF0LKVmRSwywc145UcMqmhvudbA8dcaJIh7NZhGx68LcqssTkH0LUnTIXKwPn8aVBzKc7ckHwvr+AzJSwwt9Br/St0BKhcdIiFcIkrhxs6XNCM8DqrASDYnuQUyuEOeY3iabhAMnTQrAhW7GgX4vkcX3lp+EPzFkcUVCtXag58ApwV9fYW0UOqMrzT2brB73cxQcUkU+i1wbxa1qnpXcml9dzi7XacH5y1HZ/jAOK0j1RqMA/bT1ilrnNCeh/HSjjfR5+T7IvsjYYKYx/lzaIBbN2kmnXEFwRamaOA87AzdMHOqgOVfeIr/UNIHjOo3nzVAKplXEsJ1rz2LocT+JjWGjPHUdttoWmdsOxougW4X321E2iwG6WFqxfLjtddXQRH5XN+Zjy1DGBQ5JjJRU5LdMywLqTqwWlHhTHCl8A4MZr4xX1xaiSIwWvU1HD3tk9MyVwgtECdVOJfEiUU5OrSERmrGe/Kp7/MUqnFJqyFNRlSH5N+9OPGdbF5EHSMF245VVBQ="
    - COMMIT=${TRAVIS_COMMIT::8}
    - export REPO=rdorgueil/pynode

env:
  - NODE_VERSION=6
  - NODE_VERSION=8

install:
  - curl -O -L https://github.com/grammarly/rocker/releases/download/1.3.1/rocker-1.3.1-linux_amd64.tar.gz
  - tar xvfz rocker-1.3.1-linux_amd64.tar.gz

script:
  - ./rocker build --auth $DOCKER_USER:$DOCKER_PASS --push -var TravisBuildNumber=$TRAVIS_BUILD_NUMBER -var Commit=$COMMIT -var DockerImage=$REPO:3.6-$NODE_VERSION.x -var NodeVersion=$NODE_VERSION

