# Documentation: https://confluence.atlassian.com/x/O1toN for more examples.
# image: atlassian/default-image:latest

options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - curl -SL https://github.com/grammarly/rocker/releases/download/1.3.1/rocker-1.3.1-linux_amd64.tar.gz | tar -xzC /usr/local/bin && chmod +x /usr/local/bin/rocker
          - export IMAGE_NAME=rdorgueil/pynode:$BITBUCKET_COMMIT
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
          - make
